apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoservice
  namespace: demo
spec:
  selector:
    matchLabels:
      app: demoservice
  template:
    metadata:
      labels:
        app: demoservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: saloni1814/kcdmumbai:sha-52f1e88
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: demoservice
  namespace: demo
spec:
  selector:
    app: demoservice
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort

